export type PersonaInput = {
  coreIdentity: string;
  constraints: string;
  tone: string;
  allowedToolset: string[];
};

export type PersonaDocument = PersonaInput & {
  schemaVersion: "1.0";
  generatedAt: string;
};

const ALLOWED_TOOL_PATTERN = /^[a-z0-9][a-z0-9-_]{1,31}$/i;
const MAX_FIELD_LENGTH = 2000;
const MAX_TOOLS = 64;

function normalizeText(value: unknown): string {
  if (typeof value !== "string") return "";
  return value
    .replace(/\r\n/g, "\n")
    .replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F]/g, "")
    .trim()
    .slice(0, MAX_FIELD_LENGTH);
}

function sanitizeTools(value: unknown): string[] {
  if (!Array.isArray(value)) return [];

  const cleaned = value
    .map((tool) => (typeof tool === "string" ? tool.trim() : ""))
    .filter((tool) => ALLOWED_TOOL_PATTERN.test(tool));

  return Array.from(new Set(cleaned)).slice(0, MAX_TOOLS);
}

export function compilePersonaPayload(input: unknown): PersonaInput {
  const raw = (input ?? {}) as Record<string, unknown>;

  const coreIdentity = normalizeText(raw.coreIdentity);
  const constraints = normalizeText(raw.constraints);
  const tone = normalizeText(raw.tone);
  const allowedToolset = sanitizeTools(raw.allowedToolset);

  if (!coreIdentity) {
    throw new Error("coreIdentity is required");
  }

  return {
    coreIdentity,
    constraints,
    tone,
    allowedToolset,
  };
}

export function toPersonaDocument(persona: PersonaInput): PersonaDocument {
  return {
    schemaVersion: "1.0",
    generatedAt: new Date().toISOString(),
    ...persona,
  };
}

export function generateSoulMarkdown(persona: PersonaInput): string {
  const constraints = persona.constraints || "- Respect user privacy\n- Ask before external/public actions";
  const tone = persona.tone || "Direct, practical, and calm.";

  const toolsSection = persona.allowedToolset.length
    ? persona.allowedToolset.map((tool) => `- ${tool}`).join("\n")
    : "- (inherits runtime defaults)";

  return [
    "# SOUL.md",
    "",
    "_Generated by Persona Builder_",
    "",
    "## Core Identity",
    persona.coreIdentity,
    "",
    "## Constraints",
    constraints,
    "",
    "## Tone",
    tone,
    "",
    "## Allowed Toolset",
    toolsSection,
    "",
    "## Runtime Notes",
    "- Treat user intent as the top priority.",
    "- Keep outputs concise unless detail is explicitly requested.",
  ].join("\n");
}

function yamlEscape(value: string): string {
  const safe = value.replace(/"/g, '\\"');
  return `"${safe}"`;
}

export function personaToYaml(doc: PersonaDocument): string {
  const tools = doc.allowedToolset.length
    ? doc.allowedToolset.map((tool) => `  - ${yamlEscape(tool)}`).join("\n")
    : "  - \"\"";

  return [
    `schemaVersion: ${yamlEscape(doc.schemaVersion)}`,
    `generatedAt: ${yamlEscape(doc.generatedAt)}`,
    `coreIdentity: ${yamlEscape(doc.coreIdentity)}`,
    "constraints: |-",
    ...doc.constraints.split("\n").map((line) => `  ${line}`),
    "tone: |-",
    ...doc.tone.split("\n").map((line) => `  ${line}`),
    "allowedToolset:",
    tools,
  ].join("\n");
}
